-- Do not edit this file directly. Instead use the interop library to modify the data.

--- @class table.GitD.cellData
--- @field forceIndexOn boolean

--- @class table.GitD.cellDataDefinition
--- @field data table.GitD.cellData
--- @field mesh string

--- @class table.GitD.cellDataInclude
--- @field profiles table<string, table.GitD.cellDataDefinition>
--- @field definitions table<string, string[]>

--- @type table.GitD.cellDataInclude
return {
	profiles = {
		["Force Interior Sources On"] = {
			{ mesh = "^i\\in_*", data = { forceIndexOn = true } },
		},
		["Force Exterior Sources On"] = {
			{ mesh = "^x\\ex_*", data = { forceIndexOn = true } },
		},
	},
	definitions = {
		["Vivec, Foreign Quarter Plaza"] = { "Force Exterior Sources On" },
		["Vivec, Hlaalu Plaza"] = { "Force Exterior Sources On" },
		["Vivec, Redoran Plaza"] = { "Force Exterior Sources On" },
		["Vivec, St. Delyn Plaza"] = { "Force Exterior Sources On" },
		["Vivec, St. Olms Plaza"] = { "Force Exterior Sources On" },
		["Vivec, Telvanni Plaza"] = { "Force Exterior Sources On" },
	},
}
